name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    # Uncomment when you add tests
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o publish
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: publish/

  docker:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: app
        path: publish/
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and tag Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: jobportal:latest
        load: true

    # Log in to container registry - uncomment and configure when ready to deploy
    # - name: Log in to container registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ${{ secrets.REGISTRY_URL }}
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Push image to registry - uncomment when ready to deploy
    # - name: Push Docker image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ secrets.REGISTRY_URL }}/jobportal:latest

  # Deployment job - uncomment and configure when ready to deploy
  # deploy:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   
  #   steps:
  #   - name: Deploy to Azure Web App
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: 'your-app-name'
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #       images: ${{ secrets.REGISTRY_URL }}/jobportal:latest